scalar DateTime

input NovelInput {
    title: String!
    image: String!
}

type Novel {
    id: ID!
    title: String
    image: String
    createdAt: DateTime
    updatedAt: DateTime
    authors: [Author!]
}

type Author {
    id: ID!
    name: String
    novelId: String
}

type Query {
    novel(id: ID!): Novel!
    novels: [Novel!]!
}

type Mutation {
    addNovel(data: NovelInput!): Novel!
    updateNovel(id: ID!, data: NovelInput!): Novel!
    deleteNovel(id: ID!): Novel!
    addAuthor(novelId: ID!, name: String!): Author!
    deleteAuthor(id: ID!): Author!
}
